
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry entryFilePath;

	private global::Gtk.Button buttonGetFile;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label2;

	private global::Gtk.Entry entryHundreds;

	private global::Gtk.Label label3;

	private global::Gtk.Button buttonAbout;

	private global::Gtk.Button buttonCalculate;

	private global::Gtk.Entry entryMaxCombo;

	private global::Gtk.Label label4;

	private global::Gtk.Entry entryMisses;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label5;

	private global::Gtk.CheckButton checkbuttonEasy;

	private global::Gtk.CheckButton checkbuttonNoFail;

	private global::Gtk.CheckButton checkbuttonFlashlight;

	private global::Gtk.CheckButton checkbuttonHidden;

	private global::Gtk.CheckButton checkbuttonDoubleTime;

	private global::Gtk.CheckButton checkbuttonHardRock;

	private global::Gtk.CheckButton checkbuttonHalfTime;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textviewOutput;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Taiko Difficulty Analyzer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString(".osu file path");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryFilePath = new global::Gtk.Entry();
		this.entryFilePath.CanFocus = true;
		this.entryFilePath.Name = "entryFilePath";
		this.entryFilePath.IsEditable = true;
		this.entryFilePath.InvisibleChar = '●';
		this.hbox1.Add(this.entryFilePath);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryFilePath]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonGetFile = new global::Gtk.Button();
		this.buttonGetFile.CanFocus = true;
		this.buttonGetFile.Name = "buttonGetFile";
		this.buttonGetFile.UseUnderline = true;
		this.buttonGetFile.Label = global::Mono.Unix.Catalog.GetString("Get .osu file");
		this.hbox1.Add(this.buttonGetFile);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonGetFile]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Number of 100s (default 0)");
		this.vbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryHundreds = new global::Gtk.Entry();
		this.entryHundreds.CanFocus = true;
		this.entryHundreds.Name = "entryHundreds";
		this.entryHundreds.IsEditable = true;
		this.entryHundreds.InvisibleChar = '●';
		this.vbox2.Add(this.entryHundreds);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryHundreds]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Number of misses (default 0)");
		this.vbox2.Add(this.label3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.buttonAbout = new global::Gtk.Button();
		this.buttonAbout.CanFocus = true;
		this.buttonAbout.Name = "buttonAbout";
		this.buttonAbout.UseUnderline = true;
		this.buttonAbout.Label = global::Mono.Unix.Catalog.GetString("About");
		this.vbox2.Add(this.buttonAbout);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonAbout]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.buttonCalculate = new global::Gtk.Button();
		this.buttonCalculate.CanFocus = true;
		this.buttonCalculate.Name = "buttonCalculate";
		this.buttonCalculate.UseUnderline = true;
		this.buttonCalculate.Label = global::Mono.Unix.Catalog.GetString("Calculate");
		this.vbox2.Add(this.buttonCalculate);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonCalculate]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 4;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryMaxCombo = new global::Gtk.Entry();
		this.entryMaxCombo.CanFocus = true;
		this.entryMaxCombo.Name = "entryMaxCombo";
		this.entryMaxCombo.IsEditable = true;
		this.entryMaxCombo.InvisibleChar = '●';
		this.vbox2.Add(this.entryMaxCombo);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryMaxCombo]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 5;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Max combo (default all misses at end)");
		this.vbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 6;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryMisses = new global::Gtk.Entry();
		this.entryMisses.CanFocus = true;
		this.entryMisses.Name = "entryMisses";
		this.entryMisses.IsEditable = true;
		this.entryMisses.InvisibleChar = '●';
		this.vbox2.Add(this.entryMisses);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryMisses]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 7;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox2.Add(this.vbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Mods");
		this.vbox3.Add(this.label5);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label5]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonEasy = new global::Gtk.CheckButton();
		this.checkbuttonEasy.CanFocus = true;
		this.checkbuttonEasy.Name = "checkbuttonEasy";
		this.checkbuttonEasy.Label = global::Mono.Unix.Catalog.GetString("Easy");
		this.checkbuttonEasy.DrawIndicator = true;
		this.checkbuttonEasy.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonEasy);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonEasy]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonNoFail = new global::Gtk.CheckButton();
		this.checkbuttonNoFail.CanFocus = true;
		this.checkbuttonNoFail.Name = "checkbuttonNoFail";
		this.checkbuttonNoFail.Label = global::Mono.Unix.Catalog.GetString("No Fail");
		this.checkbuttonNoFail.DrawIndicator = true;
		this.checkbuttonNoFail.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonNoFail);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonNoFail]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonFlashlight = new global::Gtk.CheckButton();
		this.checkbuttonFlashlight.CanFocus = true;
		this.checkbuttonFlashlight.Name = "checkbuttonFlashlight";
		this.checkbuttonFlashlight.Label = global::Mono.Unix.Catalog.GetString("Flashlight");
		this.checkbuttonFlashlight.DrawIndicator = true;
		this.checkbuttonFlashlight.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonFlashlight);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonFlashlight]));
		w18.PackType = ((global::Gtk.PackType)(1));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonHidden = new global::Gtk.CheckButton();
		this.checkbuttonHidden.CanFocus = true;
		this.checkbuttonHidden.Name = "checkbuttonHidden";
		this.checkbuttonHidden.Label = global::Mono.Unix.Catalog.GetString("Hidden");
		this.checkbuttonHidden.DrawIndicator = true;
		this.checkbuttonHidden.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonHidden);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonHidden]));
		w19.PackType = ((global::Gtk.PackType)(1));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonDoubleTime = new global::Gtk.CheckButton();
		this.checkbuttonDoubleTime.CanFocus = true;
		this.checkbuttonDoubleTime.Name = "checkbuttonDoubleTime";
		this.checkbuttonDoubleTime.Label = global::Mono.Unix.Catalog.GetString("Double Time/Nightcore");
		this.checkbuttonDoubleTime.DrawIndicator = true;
		this.checkbuttonDoubleTime.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonDoubleTime);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonDoubleTime]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 5;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonHardRock = new global::Gtk.CheckButton();
		this.checkbuttonHardRock.CanFocus = true;
		this.checkbuttonHardRock.Name = "checkbuttonHardRock";
		this.checkbuttonHardRock.Label = global::Mono.Unix.Catalog.GetString("Hard Rock");
		this.checkbuttonHardRock.DrawIndicator = true;
		this.checkbuttonHardRock.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonHardRock);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonHardRock]));
		w21.PackType = ((global::Gtk.PackType)(1));
		w21.Position = 6;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.checkbuttonHalfTime = new global::Gtk.CheckButton();
		this.checkbuttonHalfTime.CanFocus = true;
		this.checkbuttonHalfTime.Name = "checkbuttonHalfTime";
		this.checkbuttonHalfTime.Label = global::Mono.Unix.Catalog.GetString("Half Time");
		this.checkbuttonHalfTime.DrawIndicator = true;
		this.checkbuttonHalfTime.UseUnderline = true;
		this.vbox3.Add(this.checkbuttonHalfTime);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.checkbuttonHalfTime]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 7;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewOutput = new global::Gtk.TextView();
		this.textviewOutput.CanFocus = true;
		this.textviewOutput.Name = "textviewOutput";
		this.textviewOutput.Editable = false;
		this.textviewOutput.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkScrolledWindow.Add(this.textviewOutput);
		this.hbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
		w25.Position = 2;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w26.Position = 3;
		w26.Expand = false;
		w26.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 624;
		this.DefaultHeight = 385;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonGetFile.Clicked += new global::System.EventHandler(this.OnButtonGetFileClicked);
		this.buttonCalculate.Clicked += new global::System.EventHandler(this.OnButtonCalculateClicked);
		this.buttonAbout.Clicked += new global::System.EventHandler(this.OnButtonAboutClicked);
	}
}
